In [62]:
import requests
import pandas as pd
import random
from datetime import datetime, timedelta

In [63]:
# define a `coordinates` function:
# - taking an address as parameter
# - returning a latitude and a longitude

def coordinates(location):
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        'q': location,
        'format': 'json'
    }
    response = requests.get(url, params=params).json()
    return (response[0]['lat'], response[0]['lon'])

In [43]:
coordinates("Alexanderplatz")

{'Alexanderplatz': ('52.52197645', '13.413637435864272')}

In [76]:


# Set the number of rows for the DataFrame
num_rows = 100

# Generate random locations in Berlin
locations = ['Brandenburg Gate', 'Eisenzahnstr/westfaelischestr', 'kopenickerstr/heinrich-heine-str', 'Berlin Wall Memorial', 'Checkpoint Charlie', 'Potsdamer Platz', 'Gendarmenmarkt', 'Charlottenburg Palace', 'East Side Gallery', 'Reichstag Building']
random_locations = random.choices(locations, k=num_rows)

# Generate random times
random_times = [datetime.strptime(str(random.randint(0, 23)).zfill(2) + ':' + str(random.randint(0, 59)).zfill(2), '%H:%M').time() for _ in range(num_rows)]

# Generate random dates within the past year
end_date = datetime.now()
start_date = end_date - timedelta(days=365)
random_dates = [start_date + timedelta(days=random.randint(0, 365)) for _ in range(num_rows)]

# Create the DataFrame
data = {'Location': random_locations, 'Time': random_times, 'Date': random_dates}
df = pd.DataFrame(data)

# Save DataFrame to a CSV file
df.to_csv('berlin_data.csv', index=False)

In [77]:
df2 = pd.read_csv('berlin_data.csv')

In [78]:
# Apply the function to the 'Column1' values and create a new column
df2['Output'] = df2['Location'].apply(coordinates)

df2

,Location,Time,Date,Output
0,Reichstag Building,20:33:00,2022-07-22 20:56:44.919459,"(52.51865375, 13.376101367237903)"
1,Berlin Wall Memorial,21:54:00,2023-03-15 20:56:44.919459,"(52.537671, 13.395244908713806)"
2,East Side Gallery,21:26:00,2023-04-10 20:56:44.919459,"(52.50445415, 13.440839239027115)"
3,kopenickerstr/heinrich-heine-str,23:27:00,2022-12-31 20:56:44.919459,"(52.5110158, 13.416784)"
4,Potsdamer Platz,20:03:00,2022-07-31 20:56:44.919459,"(52.5098014, 13.375589791291057)"
...,...,...,...,...
95,Charlottenburg Palace,17:32:00,2022-12-09 20:56:44.919459,"(52.5206424, 13.292710351064521)"
96,Gendarmenmarkt,05:41:00,2022-06-27 20:56:44.919459,"(52.513636399999996, 13.392720495100818)"
97,Gendarmenmarkt,12:14:00,2022-07-29 20:56:44.919459,"(52.513636399999996, 13.392720495100818)"
98,Eisenzahnstr/westfaelischestr,18:25:00,2022-12-07 20:56:44.919459,"(52.4931447, 13.3053957)"
99,Brandenburg Gate,21:58:00,2023-04-04 20:56:44.919459,"(52.5162699, 13.377703399031432)"

In [79]:
df2['Output'][0][1]

'13.376101367237903'

In [80]:

df2['lat'] = df2['Output'].apply(lambda x : x[0])
df2['lon'] = df2['Output'].apply(lambda x : x[1])
df2

,Location,Time,Date,Output,lat,lon
0,Reichstag Building,20:33:00,2022-07-22 20:56:44.919459,"(52.51865375, 13.376101367237903)",52.51865375,13.376101367237903
1,Berlin Wall Memorial,21:54:00,2023-03-15 20:56:44.919459,"(52.537671, 13.395244908713806)",52.537671,13.395244908713806
2,East Side Gallery,21:26:00,2023-04-10 20:56:44.919459,"(52.50445415, 13.440839239027115)",52.50445415,13.440839239027115
3,kopenickerstr/heinrich-heine-str,23:27:00,2022-12-31 20:56:44.919459,"(52.5110158, 13.416784)",52.5110158,13.416784
4,Potsdamer Platz,20:03:00,2022-07-31 20:56:44.919459,"(52.5098014, 13.375589791291057)",52.5098014,13.375589791291057
...,...,...,...,...,...,...
95,Charlottenburg Palace,17:32:00,2022-12-09 20:56:44.919459,"(52.5206424, 13.292710351064521)",52.5206424,13.292710351064521
96,Gendarmenmarkt,05:41:00,2022-06-27 20:56:44.919459,"(52.513636399999996, 13.392720495100818)",52.513636399999996,13.392720495100818
97,Gendarmenmarkt,12:14:00,2022-07-29 20:56:44.919459,"(52.513636399999996, 13.392720495100818)",52.513636399999996,13.392720495100818
98,Eisenzahnstr/westfaelischestr,18:25:00,2022-12-07 20:56:44.919459,"(52.4931447, 13.3053957)",52.4931447,13.3053957
99,Brandenburg Gate,21:58:00,2023-04-04 20:56:44.919459,"(52.5162699, 13.377703399031432)",52.5162699,13.377703399031432